# Generated by Django 5.1.5 on 2025-02-03 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diets',
            new_name='Diet',
        ),
        migrations.RenameModel(
            old_name='Intolerances',
            new_name='Intolerance',
        ),
        migrations.RenameModel(
            old_name='Recepies',
            new_name='Recepie',
        ),
    ]
