# Generated by Django 5.1.5 on 2025-02-03 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_diets_diet_rename_intolerances_intolerance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='diets',
        ),
        migrations.AddField(
            model_name='user',
            name='diet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.diet'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
