# Generated by Django 5.1.6 on 2025-02-11 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_diets_user_diet_alter_diet_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recepie',
            new_name='Recipie',
        ),
        migrations.RenameField(
            model_name='recipie',
            old_name='recepie_id',
            new_name='recipie_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='liked_recepies',
            new_name='liked_recipies',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='saved_recepies',
            new_name='saved_recipies',
        ),
    ]
