# Generated by Django 5.1.6 on 2025-02-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_recepie_recipie_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipie',
            new_name='Recipe',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipie_id',
            new_name='recipe_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='liked_recipies',
            new_name='liked_recipes',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='saved_recipies',
            new_name='saved_recipes',
        ),
    ]
