# Generated by Django 5.1.6 on 2025-02-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_recipie_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='diet_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intolerance',
            name='intolerance_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
