# Generated by Django 5.1.6 on 2025-02-15 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_diet_diet_id_intolerance_intolerance_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='diet_id',
        ),
        migrations.RemoveField(
            model_name='intolerance',
            name='intolerance_id',
        ),
    ]
