# Generated by Django 5.1.6 on 2025-03-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_saved_recipes_remove_user_liked_recipes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_recipes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_recipes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
